### PR TITLE
feat: created option to create the module async

### PR DESCRIPTION
**Pull request by YotamZiv298**
Created option to create the module asynchronously so `ConfigService` will be injectable.

### CODE REVIEW

**Comment by YotamZiv298** [comment]
@yoni123100 please review

**Comment by yoni123100** [comment]
Hi @YotamZiv298 !

What's the purpose of creating an asynchronous provider for a logger? 
Is `BetterLoggerSettings` (aka logger's configuration) going to be loaded asynchronously? For example fetching logger's configuration from an external source, like a database.

**Comment by YotamZiv298** [comment]
Hey,

I wanted to load the `serviceName` option from `ConfigService` and not use a literal `string`.

I think that'll solve the problem I'm facing, isn't it?

**Comment by YotamZiv298** [comment]
@yoni123100 Could you publish the new version in NPM? 😅

**Pull request merged**
